modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "accessories"
version = "${version}"
displayName = "Accessories"
authors = "Blodhgarm, chyzman, Dr.Zeal"
credits = "Special thanks to both Emi and C4 for the creation of both Trinkets and Curios"
description = '''
A extendable and data-driven Accessory Mod for Minecraft.
'''
logoFile = "icon.png"

[[mixins]]
config = 'accessories-common.mixins.json'
[[mixins]]
config = 'accessories-forge.mixins.json'

[[dependencies.accessories]]
modId = "neoforge"
required = true
versionRange = "[20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.accessories]]
modId = "minecraft"
required = true
versionRange = "[1.20.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.accessories]]
modId = "cloth_config"
required = true
versionRange = "[13,)"
ordering = "NONE"
side = "BOTH"
